---
linux: #Группа хостов 
  children: #Обозначение, что будет подгруппа хостов
    nginx_proxy: #Имя подгруппы хостов
      hosts: #Узлы группы
        vm_1: #Имя машины
          ansible_host: 158.160.54.83 #Адрес машины
          ip_vm2: 130.193.49.31
    nginx: #Имя подгруппы хостов
      hosts: #Узлы группы
        vm_2: #Имя машины
          ansible_host: 130.193.49.31 #Адрес машины
        vm_3: #Имя машины
          ansible_host: 158.160.61.58 #Адрес машины
  vars: #Переменные, доступные или используемые для всех подгрупп
    ansible_user: "ubuntu"
    ansible_ssh_private_key_file: "~/.ssh/id_ed25519"
    connection_protocol: ssh #тип подключения
    ansible_become: true
